JCC	=	javac

JFLAGS	=	-g

default:	ConnectDB.class	StoreManager.class	Supplier.class

ConnectDB.class:	ConnectDB.java
	$(JCC)	$(JFLAGS)	ConnectDB.java

StoreManager.class:	StoreManager.java
	$(JCC)	$(JFLAGS)	StoreManager.java

Supplier.class:	Supplier.java
	$(JCC)	$(JFLAGS)	Supplier.java

clean:
	$(RM)	*.class


